# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activity_tower_defense_tower.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"activity_tower_defense_tower.proto\x12\x1c\x61\x63tivity_tower_defense_tower\"\xdf\x02\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nActivityId\x18\x02 \x01(\x05\x12\x0c\n\x04Type\x18\x03 \x01(\x05\x12\x0c\n\x04Icon\x18\x04 \x01(\t\x12\x0c\n\x04Name\x18\x05 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x06 \x01(\t\x12\x11\n\tCondition\x18\x07 \x01(\x05\x12\x12\n\nIconBattle\x18\x08 \x01(\t\x12\x12\n\nDescBattle\x18\t \x03(\t\x12\x13\n\x0bUpgradeCost\x18\n \x01(\x05\x12\x17\n\x0f\x44ismantleReturn\x18\x0b \x01(\x05\x12\x0f\n\x07SubType\x18\x0c \x01(\x05\x12\x0f\n\x07MiniTip\x18\r \x01(\t\x12\x10\n\x08SubArray\x18\x0e \x03(\x05\x12\r\n\x05Title\x18\x0f \x01(\t\x12\x0e\n\x06RoleId\x18\x10 \x01(\x05\x12\x14\n\x0c\x42uffConfigId\x18\x11 \x01(\x05\x12\x19\n\x11UpgradeCountLimit\x18\x12 \x01(\x05\x12\x13\n\x0b\x41ttackRange\x18\x13 \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'activity_tower_defense_tower_pb2'
  # @@protoc_insertion_point(class_scope:activity_tower_defense_tower.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=69
  _CFG._serialized_end=420
# @@protoc_insertion_point(module_scope)
