# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: affix_type.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x66\x66ix_type.proto\x12\naffix_type\"\xc8\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x18\n\x10\x45xtraDescription\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x03(\x05\x12\x13\n\x0b\x41\x66\x66ixBuffId\x18\x05 \x01(\x05\x12\x0e\n\x06\x42uffid\x18\x06 \x03(\x05\x12\x10\n\x08MaxLevel\x18\x07 \x01(\x05\x12\x0f\n\x07LogicId\x18\x08 \x01(\x05\x12\x0c\n\x04\x42\x61se\x18\t \x03(\x05\x12\x0e\n\x06\x46\x61\x63tor\x18\n \x03(\x05\x12\x12\n\nFlowscript\x18\x0b \x03(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'affix_type_pb2'
  # @@protoc_insertion_point(class_scope:affix_type.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=33
  _CFG._serialized_end=233
# @@protoc_insertion_point(module_scope)
