# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_chip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rai_chip.proto\x12\x07\x61i_chip\"\xc0\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0e\n\x06TypeId\x18\x02 \x01(\x05\x12\x10\n\x08SpecChar\x18\x03 \x01(\x05\x12\x10\n\x08SuitName\x18\x04 \x01(\t\x12\x11\n\tPictureId\x18\x05 \x01(\t\x12\x10\n\x08Portrait\x18\x06 \x01(\t\x12\x14\n\x0cNewCondition\x18\x07 \x01(\x05\x12\x10\n\x08\x46lowName\x18\x08 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\t \x01(\t\x12\x0f\n\x07Profile\x18\n \x01(\t\x12\r\n\x05Story\x18\x0b \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'ai_chip_pb2'
  # @@protoc_insertion_point(class_scope:ai_chip.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=27
  _CFG._serialized_end=219
# @@protoc_insertion_point(module_scope)
