# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cooperate_unique_skill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ooperate_unique_skill.proto\x12\x16\x63ooperate_unique_skill\"\x95\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x18\n\x10\x43ooperateRoleIds\x18\x02 \x03(\x05\x12\x1a\n\x12\x43ooperateThrownIds\x18\x03 \x03(\x05\x12\x12\n\nPrefabPath\x18\x04 \x01(\t\x12\x15\n\rEndPrefabPath\x18\x05 \x01(\t\x12\x0f\n\x07SkillId\x18\x06 \x01(\x05\x12\x10\n\x08IconPath\x18\x07 \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'cooperate_unique_skill_pb2'
  # @@protoc_insertion_point(class_scope:cooperate_unique_skill.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=57
  _CFG._serialized_end=206
# @@protoc_insertion_point(module_scope)
