# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: description.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65scription.proto\x12\x0b\x64\x65scription\"v\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x13\n\x0b\x44\x65scription\x18\x02 \x01(\t\x12(\n\x05Param\x18\x03 \x03(\x0b\x32\x19.description.Cfg.StrArray\x1a$\n\x08StrArray\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04\x44\x61ta\x18\x02 \x03(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
_CFG_STRARRAY = _CFG.nested_types_by_name['StrArray']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {

  'StrArray' : _reflection.GeneratedProtocolMessageType('StrArray', (_message.Message,), {
    'DESCRIPTOR' : _CFG_STRARRAY,
    '__module__' : 'description_pb2'
    # @@protoc_insertion_point(class_scope:description.Cfg.StrArray)
    })
  ,
  'DESCRIPTOR' : _CFG,
  '__module__' : 'description_pb2'
  # @@protoc_insertion_point(class_scope:description.Cfg)
  })
_sym_db.RegisterMessage(Cfg)
_sym_db.RegisterMessage(Cfg.StrArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=34
  _CFG._serialized_end=152
  _CFG_STRARRAY._serialized_start=116
  _CFG_STRARRAY._serialized_end=152
# @@protoc_insertion_point(module_scope)
