# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HitAudio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eHitAudio.proto\x12\x08HitAudio\"\x85\x04\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12,\n\x06Weapon\x18\x02 \x01(\x0e\x32\x1c.HitAudio.Cfg.WeaponCategory\x12(\n\x04Role\x18\x03 \x01(\x0e\x32\x1a.HitAudio.Cfg.RoleCategory\x12\x15\n\rAudioClipPath\x18\x04 \x01(\t\"\x91\x02\n\x0eWeaponCategory\x12\x17\n\x13WeaponCategory_None\x10\x00\x12\x18\n\x14WeaponCategory_Sword\x10\x01\x12\x1e\n\x1aWeaponCategory_LongHandled\x10\x02\x12\x16\n\x12WeaponCategory_Bow\x10\x03\x12\x18\n\x14WeaponCategory_Blunt\x10\x04\x12\x16\n\x12WeaponCategory_Gun\x10\x05\x12\x17\n\x13WeaponCategory_Claw\x10\x06\x12\x17\n\x13WeaponCategory_Body\x10\x07\x12\x18\n\x14WeaponCategory_Magic\x10\x08\x12\x16\n\x12WeaponCategory_Orb\x10\t\"o\n\x0cRoleCategory\x12\x15\n\x11RoleCategory_None\x10\x00\x12\x16\n\x12RoleCategory_Human\x10\x06\x12\x18\n\x14RoleCategory_Virtual\x10\x07\x12\x16\n\x12RoleCategory_Metal\x10\x08\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
_CFG_WEAPONCATEGORY = _CFG.enum_types_by_name['WeaponCategory']
_CFG_ROLECATEGORY = _CFG.enum_types_by_name['RoleCategory']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'HitAudio_pb2'
  # @@protoc_insertion_point(class_scope:HitAudio.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=29
  _CFG._serialized_end=546
  _CFG_WEAPONCATEGORY._serialized_start=160
  _CFG_WEAPONCATEGORY._serialized_end=433
  _CFG_ROLECATEGORY._serialized_start=435
  _CFG_ROLECATEGORY._serialized_end=546
# @@protoc_insertion_point(module_scope)
