# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HitFeedback.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11HitFeedback.proto\x12\x0bHitFeedback\"/\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x1c\n\x14\x44\x65\x66\x61ultAnimationName\x18\x02 \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'HitFeedback_pb2'
  # @@protoc_insertion_point(class_scope:HitFeedback.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=34
  _CFG._serialized_end=81
# @@protoc_insertion_point(module_scope)
