# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockedCameraParam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17LockedCameraParam.proto\x12\x11LockedCameraParam\"Z\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nLockHeight\x18\x02 \x01(\x02\x12\x12\n\nLockRadius\x18\x03 \x01(\x02\x12\x0f\n\x07ScreenY\x18\x04 \x01(\x02\x12\x0e\n\x06Remark\x18\x05 \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'LockedCameraParam_pb2'
  # @@protoc_insertion_point(class_scope:LockedCameraParam.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=46
  _CFG._serialized_end=136
# @@protoc_insertion_point(module_scope)
