# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monster_standard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16monster_standard.proto\x12\x10monster_standard\"\xb2\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0f\n\x07\x41ttack1\x18\x02 \x01(\x05\x12\x10\n\x08\x44\x65\x66\x65nse1\x18\x03 \x01(\x05\x12\x0b\n\x03Hp1\x18\x04 \x01(\x05\x12\x0f\n\x07\x41ttack2\x18\x05 \x01(\x05\x12\x10\n\x08\x44\x65\x66\x65nse2\x18\x06 \x01(\x05\x12\x0b\n\x03Hp2\x18\x07 \x01(\x05\x12\x0f\n\x07\x41ttack3\x18\x08 \x01(\x05\x12\x10\n\x08\x44\x65\x66\x65nse3\x18\t \x01(\x05\x12\x0b\n\x03Hp3\x18\n \x01(\x05\x12\x0f\n\x07HpRatio\x18\x0b \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'monster_standard_pb2'
  # @@protoc_insertion_point(class_scope:monster_standard.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=45
  _CFG._serialized_end=223
# @@protoc_insertion_point(module_scope)
