# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_skill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12public_skill.proto\x12\x0cpublic_skill\"\xc3\x02\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\n\n\x02\x43\x64\x18\x02 \x01(\x05\x12\x14\n\x0cHitDamagePec\x18\x03 \x03(\x05\x12\x14\n\x0cHitDamageGrp\x18\x04 \x03(\x05\x12\x17\n\x0fSkillDamageType\x18\x05 \x01(\x05\x12\r\n\x05Range\x18\x06 \x01(\x05\x12\x13\n\x0bMaxUseCount\x18\x07 \x01(\x05\x12\x1b\n\x13\x42\x61lanceValueConsume\x18\x08 \x03(\x05\x12\x14\n\x0c\x45nergyChange\x18\t \x01(\x05\x12\x17\n\x0fHighDamageIndex\x18\n \x03(\x05\x12\x14\n\x0cSkillSubType\x18\x0b \x01(\x05\x12\x12\n\nSkillIndex\x18\x0c \x01(\x05\x12\x11\n\tSkillType\x18\r \x01(\x05\x12\x17\n\x0f\x41\x62ilityCategory\x18\x0e \x01(\x05\x12\x19\n\x11\x42reakValueConsume\x18\x0f \x03(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'public_skill_pb2'
  # @@protoc_insertion_point(class_scope:public_skill.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=37
  _CFG._serialized_end=360
# @@protoc_insertion_point(module_scope)
