# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Skin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nSkin.proto\x12\x04Skin\"\xe3\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Hero\x18\x02 \x01(\x05\x12\x17\n\x0f\x42\x61ttleModelPath\x18\x03 \x01(\t\x12\x19\n\x11\x42\x61ttleCameraParam\x18\x04 \x01(\x05\x12\x17\n\x0fTransfiguration\x18\x05 \x01(\x05\x12\x16\n\x0eRenderTimeline\x18\x06 \x01(\t\x12\x18\n\x10RenderFlowscript\x18\x07 \x01(\t\x12%\n\x1d\x41\x64\x64itionalRenderTimelineArray\x18\x08 \x03(\t\x12\x1c\n\x14SourceSpaceAssetPath\x18\t \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'Skin_pb2'
  # @@protoc_insertion_point(class_scope:Skin.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=21
  _CFG._serialized_end=248
# @@protoc_insertion_point(module_scope)
