# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weapon_effect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13weapon_effect.proto\x12\rweapon_effect\"\xb7\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x13\n\x0b\x44\x65scription\x18\x02 \x03(\x05\x12/\n\nLevelParam\x18\x03 \x03(\x0b\x32\x1b.weapon_effect.Cfg.IntArray\x12\x10\n\x08SpecChar\x18\x04 \x03(\x05\x12\x10\n\x08\x46lowName\x18\x05 \x03(\t\x12\x14\n\x0cTimelinePath\x18\x06 \x01(\t\x1a$\n\x08IntArray\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04\x44\x61ta\x18\x02 \x03(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
_CFG_INTARRAY = _CFG.nested_types_by_name['IntArray']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {

  'IntArray' : _reflection.GeneratedProtocolMessageType('IntArray', (_message.Message,), {
    'DESCRIPTOR' : _CFG_INTARRAY,
    '__module__' : 'weapon_effect_pb2'
    # @@protoc_insertion_point(class_scope:weapon_effect.Cfg.IntArray)
    })
  ,
  'DESCRIPTOR' : _CFG,
  '__module__' : 'weapon_effect_pb2'
  # @@protoc_insertion_point(class_scope:weapon_effect.Cfg)
  })
_sym_db.RegisterMessage(Cfg)
_sym_db.RegisterMessage(Cfg.IntArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=39
  _CFG._serialized_end=222
  _CFG_INTARRAY._serialized_start=186
  _CFG_INTARRAY._serialized_end=222
# @@protoc_insertion_point(module_scope)
