# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: charactor_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63haractor_param.proto\x12\x0f\x63haractor_param\"\x8a\x03\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nAttackRate\x18\x02 \x01(\x05\x12\x19\n\x11TargetDebuffArray\x18\x03 \x03(\x05\x12\x14\n\x0c\x42\x65stDistance\x18\x04 \x01(\x05\x12\x18\n\x10\x41pproachDistance\x18\x05 \x01(\x05\x12\x0c\n\x04Name\x18\x06 \x01(\t\x12\x10\n\x08HeadIcon\x18\x07 \x01(\t\x12\x12\n\nEnergyType\x18\x08 \x01(\x05\x12\x16\n\x0e\x45nergyMaxValue\x18\t \x01(\x05\x12\x19\n\x11MaxEnduranceValue\x18\n \x01(\x05\x12\x1d\n\x15\x43onsumeEnduranceValue\x18\x0b \x01(\x05\x12\x1c\n\x14ResumeEnduranceSpeed\x18\x0c \x01(\x05\x12\x0e\n\x06RaceID\x18\r \x01(\x05\x12\x17\n\x0fUltimateAvoidCD\x18\x0e \x01(\x05\x12\x18\n\x10ItemPickUpRadius\x18\x0f \x01(\x05\x12\x1e\n\x16UltimateAvoidSpaceTime\x18\x10 \x01(\x05\x12\x11\n\tRangeType\x18\x11 \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'charactor_param_pb2'
  # @@protoc_insertion_point(class_scope:charactor_param.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=43
  _CFG._serialized_end=437
# @@protoc_insertion_point(module_scope)
