# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: equip_skill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65quip_skill.proto\x12\x0b\x65quip_skill\"\xf6\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x13\n\x0b\x44\x65scNoValue\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\x12\x15\n\rDescSpecValue\x18\x05 \x01(\t\x12\x15\n\rEquipEffectId\x18\x06 \x01(\x05\x12\x11\n\tAttribute\x18\x07 \x01(\x05\x12\x0f\n\x07Upgrade\x18\x08 \x01(\x05\x12\r\n\x05Lvmax\x18\t \x01(\x05\x12\x0f\n\x07Percent\x18\n \x01(\x05\x12\x0c\n\x04Icon\x18\x0b \x01(\t\x12\x0c\n\x04Type\x18\x0c \x01(\x05\x12\x11\n\tTypeInner\x18\r \x01(\x05\x12\x11\n\tSkillType\x18\x0e \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'equip_skill_pb2'
  # @@protoc_insertion_point(class_scope:equip_skill.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=35
  _CFG._serialized_end=281
# @@protoc_insertion_point(module_scope)
