# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_buff.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11public_buff.proto\x12\x0bpublic_buff\"\xf8\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Type\x18\x02 \x01(\t\x12\x0f\n\x07SubType\x18\x03 \x01(\t\x12\x10\n\x08MaxLevel\x18\x04 \x01(\x05\x12\x13\n\x0b\x42uffClassId\x18\x05 \x01(\x05\x12\x10\n\x08\x45\x66\x66\x65\x63tId\x18\x06 \x01(\x05\x12\x0c\n\x04Icon\x18\x07 \x01(\t\x12\x10\n\x08KeepTime\x18\x08 \x01(\x05\x12\x14\n\x0cKeepTimeGrow\x18\t \x01(\x05\x12\x14\n\x0c\x42uffTicktime\x18\n \x01(\x05\x12\x11\n\tDelaytime\x18\x0b \x01(\x05\x12\x15\n\rBuffparamBase\x18\x0c \x03(\x05\x12\x17\n\x0f\x42uffparamFactor\x18\r \x03(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'public_buff_pb2'
  # @@protoc_insertion_point(class_scope:public_buff.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=35
  _CFG._serialized_end=283
# @@protoc_insertion_point(module_scope)
