# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RoleVoice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRoleVoice.proto\x12\tRoleVoice\"\x8b\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tSheetName\x18\x02 \x01(\t\x12\x0f\n\x07\x43ueName\x18\x03 \x01(\t\x12\x11\n\tUseStream\x18\x04 \x01(\x08\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\x05\x12\n\n\x02\x43\x64\x18\x06 \x01(\x05\x12\x13\n\x0bInfluenceId\x18\x07 \x03(\x05\x12\x0f\n\x07\x41\x64\x64Time\x18\x08 \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'RoleVoice_pb2'
  # @@protoc_insertion_point(class_scope:RoleVoice.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=31
  _CFG._serialized_end=170
# @@protoc_insertion_point(module_scope)
