# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneMap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSceneMap.proto\x12\x08SceneMap\"\xc9\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x13\n\x0bMapDataPath\x18\x02 \x01(\t\x12\x15\n\rExternalParam\x18\x03 \x01(\t\x12\x10\n\x08\x43ueSheet\x18\x04 \x01(\t\x12\x0f\n\x07\x43ueName\x18\x05 \x01(\t\x12\x0e\n\x06\x43ueAwb\x18\x06 \x01(\t\x12\x10\n\x08SpCharID\x18\x07 \x03(\x05\x12\x13\n\x0bSpLogicPath\x18\x08 \x03(\t\x12\x19\n\x11SpBattlePanelPath\x18\t \x01(\t\x12\x15\n\rSkipWinAction\x18\n \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'SceneMap_pb2'
  # @@protoc_insertion_point(class_scope:SceneMap.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=29
  _CFG._serialized_end=230
# @@protoc_insertion_point(module_scope)
