# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UIAudio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rUIAudio.proto\x12\x07UIAudio\"i\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tSourceKey\x18\x02 \x01(\t\x12\x10\n\x08\x43ueSheet\x18\x03 \x01(\t\x12\x0f\n\x07\x43ueName\x18\x04 \x01(\t\x12\x0e\n\x06\x43ueAwb\x18\x05 \x01(\t\x12\x10\n\x08\x44\x65scribe\x18\x06 \x01(\tb\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'UIAudio_pb2'
  # @@protoc_insertion_point(class_scope:UIAudio.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=26
  _CFG._serialized_end=131
# @@protoc_insertion_point(module_scope)
