# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UniqueSkill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11UniqueSkill.proto\x12\x0bUniqueSkill\"\x9e\x01\n\x03\x43\x66g\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nUpperLimit\x18\x02 \x01(\x05\x12\x14\n\x0c\x42\x61seAddValue\x18\x03 \x01(\x05\x12\x0c\n\x04Tick\x18\x04 \x01(\x05\x12\x11\n\tAbilityId\x18\x05 \x03(\x05\x12\x13\n\x0bProjectiles\x18\x06 \x03(\x05\x12\x17\n\x0f\x41\x64\x64itionalValue\x18\x07 \x01(\x05\x12\x12\n\nAiDistance\x18\x08 \x01(\x05\x62\x06proto3')



_CFG = DESCRIPTOR.message_types_by_name['Cfg']
Cfg = _reflection.GeneratedProtocolMessageType('Cfg', (_message.Message,), {
  'DESCRIPTOR' : _CFG,
  '__module__' : 'UniqueSkill_pb2'
  # @@protoc_insertion_point(class_scope:UniqueSkill.Cfg)
  })
_sym_db.RegisterMessage(Cfg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFG._serialized_start=35
  _CFG._serialized_end=193
# @@protoc_insertion_point(module_scope)
